version: '2'
services:
  server:
    build:
      context: ./api/
    command: /usr/app/node_modules/.bin/nodemon src/index.js
    volumes:
      - ./api/:/usr/app
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
  client:
    build:
      context: ./client/
    command: npm start
    volumes:
      - ./client/:/app
      - /app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
